### Read training, dev and unlabeled test data

The following provides a starting code (Python 3) of how to read the labeled training and dev cipher text, and unlabeled test cipher text, into lists.

In [ ]:
train, dev, test = [], [], []

In [ ]:
for x in open('./train_enc.tsv', encoding='utf-8'):
    x = x.rstrip('\n\r').split('\t')
    # x[0] will be the label (0 or 1), and x[1] will be the ciphertext sentence.
    x[0] = int(x[0]) 
    train.append(x)
print (len(train))
print (train[:3])

16220
[[0, 'lkêcê yoúc cêêö y#êjl lw mówám Újám j Úêê# ütlk Úol lkêú z#ê ctöé8ú ówl xoóóú éê#xw#öê#c .'], [0, '6êcétlê jolêot8 zc éê#xw#öjóáê , tl zc j #jlkê# 8tcl8êcc jöÚ8ê 6wüó lkê öt668ê wx lkê #wj6 , ükê#ê lkê lkêöjltá t#wótêc j#ê lww wÚ2twoc jó6 lkê cê+oj8 éw8tltác lww cöoy .'], [0, 'tx lktc kw8t6jú öw2tê tc coééwcê6 lw Úê j ytxl , cwöêÚw6ú oóü#jééê6 tl êj#8ú , lwwm wol j88 lkê yww6 cloxx , jó6 8êxl Úêktó6 lkê á#jé ( 8tlê#j88ú ) .']]


In [ ]:
for x in open('./dev_enc.tsv', encoding='utf-8'):
    x = x.rstrip('\n\r').split('\t')
    # x[0] will be the label (0 or 1), and x[1] will be the ciphertext sentence.
    x[0] = int(x[0]) 
    dev.append(x)
print (len(dev))
print (dev[:3])

2027
[[1, 'ów8jó Ú#j2ê8ú l#êj6c ükê#ê xêü jöê#tájó xt8öc 6j#ê lw 6ê82ê 77 tólw lkê üw#86 wx jöÚt2j8êóáê jó6 jöÚtyotlú <<<'], [0, 'ê2êó öo#ékú zc ê+éê#l áwötá ltötóy jó6 xjöê6 ákj#tcöj áj ózl #êcáoê lktc êxxw#l .'], [1, 'üt88 jcco#ê68ú #jóm jc wóê wx lkê á8ê2ê#êcl , öwcl 6êáêélt2ê8ú jöoctóy áwöê6têc wx lkê úêj# .']]


#### Different from 'train' and 'dev' that are both list of tuples, 'test' will be just a list.

In [ ]:
for x in open('./test_enc_unlabeled.tsv', encoding='utf-8'):
    x = x.rstrip('\n\r')
    test.append(x)
print (len(test))
print (test[:3])

2028
['j 6t6jáltá jó6 6o88 6wáoöêólj#ú y8w#txútóy cwxlüj#ê jój#ákú .', 'ówlktóy cltámc , #êj88ú , ê+áêél j 8tóyê#tóy á#êêétóêcc wóê xêê8c x#wö Úêtóy 6#jyyê6 lk#woyk j cj6 , cw#6t6 oót2ê#cê wx yoóc , 6#oyc , j2j#táê jó6 6jöjyê6 6#êjöc .', 'öo#ékú jó6 üt8cwó jáloj88ú öjmê j é#êllú yww6 lêjö <<< Úol lkê é#wvêál co##woó6tóy lkêö tc 6tcl#êcctóy8ú #wlê .']


#### You can split every sentence into lists of words by white spaces.

In [ ]:
train_split = [[x[0], x[1].split(' ')] for x in train]
dev_split = [[x[0], x[1].split(' ')] for x in dev]
test_split = [[x.split(' ')] for x in test]

### Main Code Body

You may choose to experiment with different methods using your program. However, you need to embed the training and inference processes at here. We will use your prediction on the unlabeled test data to grade, while checking this part to understand how your method has produced the predictions.

In [ ]:
# Eventually, results need to be a list of 2028 0 or 1's
results = []

In [ ]:
import pandas as pd
training_data=[]
for i in train_split:
  training_data.append(i[1])
dev_data=[]
for i in dev_split:
  dev_data.append(i[1])
df1=pd.DataFrame(training_data)
test_data=[]
for i in test_split:
  test_data.append(i[0])
df1=pd.DataFrame(training_data)
length_t_data=df1.shape[1]
df2=pd.DataFrame(dev_data)
length_d_data=df2.shape[1]
df3=pd.DataFrame(test_data)
length_test_data=df3.shape[1]
max_length_val1=max(length_t_data,length_d_data,length_test_data)
max_length_val1

59

In [ ]:
dict_vocab_train=dict()
for i in training_data:
  for j,k in enumerate(i):
    if(k not in dict_vocab_train):
      dict_vocab_train[k]=1
    else:
      dict_vocab_train[k]=dict_vocab_train[k]+1
dict_vocab_train=sorted(dict_vocab_train.items(),key=lambda a:a[1],reverse=True)
dict_vocab_train=dict(dict_vocab_train)
dict_vocab_train

In [ ]:
dict_vocab_dev=dict()
for i in dev_data:
  for j,k in enumerate(i):
    if(k not in dict_vocab_dev):
      dict_vocab_dev[k]=1
    else:
      dict_vocab_dev[k]=dict_vocab_dev[k]+1
dict_vocab_dev=sorted(dict_vocab_dev.items(),key=lambda a:a[1],reverse=True)
dict_vocab_dev=dict(dict_vocab_dev)
dict_vocab_dev

In [ ]:
stop_words_train=[]
for i in range(15):
  a=dict_vocab_train.popitem()
  stop_words_train.append(a[0])
stop_words_train=set(stop_words_train)
stop_words_train

In [ ]:
stop_words_dev=[]
for i in range(15):
  a=dict_vocab_dev.popitem()
  stop_words_dev.append(a[0])
stop_words_dev=set(stop_words_dev)
stop_words_dev
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop=set(stopwords.words("english"))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
import pandas as pd
df1=pd.DataFrame(train,columns=['labels','ciphertext'])
df2=pd.DataFrame(dev,columns=['labels','ciphertext'])
df3=pd.DataFrame(test,columns=['ciphertext'])
import re
import string
def re_tag(ciphertext):
    temp=re.compile(r"https?://\S+|www\.\S+")
    return(temp.sub(r"",ciphertext))
def temp_pun(ciphertext):
    temp=str.maketrans("", "", string.punctuation)
    return(ciphertext.translate(temp))
def re_ht(ciphertext):
    temp=re.compile(r"<.*?>")
    return(temp.sub(r"",ciphertext))
df1["ciphertext"] = df1.ciphertext.map(lambda x:temp_pun(x))
df1["ciphertext"] = df1.ciphertext.map(lambda x:re_ht(x))
df1["ciphertext"] = df1.ciphertext.map(lambda x:re_tag(x))
df2["ciphertext"] = df2.ciphertext.map(lambda x:temp_pun(x))
df2["ciphertext"] = df2.ciphertext.map(lambda x:re_ht(x))
df2["ciphertext"] = df2.ciphertext.map(lambda x:re_tag(x))
df3["ciphertext"] = df3.ciphertext.map(lambda x:re_ht(x))
df3["ciphertext"] = df3.ciphertext.map(lambda x:re_tag(x))

In [ ]:
def remove_stopwords(text):
    data=[i.lower() for i in text.split() if i.lower() not in stop]
    return(" ".join(data))
df1["ciphertext"]=df1["ciphertext"].map(remove_stopwords)
df2["ciphertext"]=df2["ciphertext"].map(remove_stopwords)
df3["ciphertext"]=df3["ciphertext"].map(remove_stopwords)

In [ ]:
from collections import Counter
def count_train_dev(text):
    count=Counter()
    for i in text.values:
        for j in i.split():
            count[j]+=1
    return(count)
text_train=df1.ciphertext
counter_train_val=count_train_dev(df1.ciphertext)
text_dev=df2.ciphertext
counter_dev_val=count_train_dev(text_dev)

In [ ]:
length_train_count,length_dev_count=len(counter_train_val),len(counter_dev_val)

In [ ]:
length_train_count

20065

In [ ]:
length_dev_count

7475

In [ ]:
words_train_num=length_train_count

In [ ]:
from keras.preprocessing.text import Tokenizer
tokenizer=Tokenizer(num_words=words_train_num)
tokenizer.fit_on_texts(df1.ciphertext)
vocab_size=len(tokenizer.word_index)+1

In [ ]:
word_index=tokenizer.word_index
word_index

In [ ]:
seq_train=tokenizer.texts_to_sequences(df1.ciphertext)
seq_dev=tokenizer.texts_to_sequences(df2.ciphertext)
seq_test=tokenizer.texts_to_sequences(df3.ciphertext)
seq_train[0]

[192, 589, 240, 134, 5, 4502, 225, 2, 6011, 11, 13, 82, 286, 299, 24, 70, 1263]

In [ ]:
seq_dev[0]

In [ ]:
seq_test[0]

[2, 3859, 3, 268, 617, 1103, 13896]

In [ ]:
!wget -P /root/input/ -c "https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz"

--2022-03-24 12:23:12--  https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.217.11.54
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.217.11.54|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1647046227 (1.5G) [application/x-gzip]
Saving to: ‘/root/input/GoogleNews-vectors-negative300.bin.gz’

GoogleNews-vectors- 100%[===================>]   1.53G  51.3MB/s    in 27s     

2022-03-24 12:23:40 (57.2 MB/s) - ‘/root/input/GoogleNews-vectors-negative300.bin.gz’ saved [1647046227/1647046227]



In [ ]:
emb_file='/root/input/GoogleNews-vectors-negative300.bin.gz'

In [ ]:
import gensim
from gensim.models import word2vec
from gensim.models import KeyedVectors
from sklearn.metrics.pairwise import cosine_similarity
embed_size=300
indx={}
word_vectors=KeyedVectors.load_word2vec_format(emb_file,binary=True)

In [ ]:
train_w2v_model=gensim.models.Word2Vec(sentences=str(seq_train),size=300,window=10,min_count=1)
dev_w2v_model=gensim.models.Word2Vec(sentences=str(seq_dev),size=300,window=10,min_count=1)

In [ ]:
train_w2v_model.train(seq_train,epochs=10,total_examples=len(seq_train))

(0, 2921690)

In [ ]:
dev_w2v_model.train(seq_dev,epochs=10,total_examples=len(seq_dev))

(0, 350120)

In [ ]:
vocab=train_w2v_model.wv.vocab
len(vocab)

14

In [ ]:
vocab

In [ ]:
vocab=list(vocab)
word_vec_dict={}
for word in vocab:
  word_vec_dict[word]=train_w2v_model.wv.get_vector(word)
word_vec_dict

In [ ]:
import numpy as np
dimen=300
mat_emb=np.zeros(shape=(vocab_size,dimen))
for i,j in tokenizer.word_index.items():
  embed_vector=word_vec_dict.get(i)
  if embed_vector is not None:  
    mat_emb[j]=embed_vector
max_length_val=20

In [ ]:
from keras.preprocessing.sequence import pad_sequences
padd,trun="post","post"
train_padding=pad_sequences(seq_train,maxlen=20,padding=padd,truncating=trun)
dev_padding=pad_sequences(seq_dev,maxlen=20,padding=padd,truncating=trun)
test_padding=pad_sequences(seq_test,maxlen=20,padding=padd,truncating=trun)

In [ ]:
train_padding[0]
train_padding.shape

(16220, 20)

In [ ]:
dev_padding[0]

array([ 6858, 17073,  4141,   189,   162,   195,   113,  2975,     5,
       17074,    33,    48,     1,   161,     4,  8801,     3,  2795,
           0,     0], dtype=int32)

In [ ]:
test_padding[0]

array([    2,  3859,     3,   268,   617,  1103, 13896,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0], dtype=int32)

In [ ]:
print(df1.ciphertext[0])
print(seq_train[0])

lkêcê yoúc cêêö yêjl lw mówám újám j úêê ütlk úol lkêú zê ctöé8ú ówl xoóóú éêxwöêc
[192, 589, 240, 134, 5, 4502, 225, 2, 6011, 11, 13, 82, 286, 299, 24, 70, 1263]


In [ ]:
train_padding.shape,dev_padding.shape

((16220, 20), (2027, 20))

In [ ]:
from keras.models import Model
from keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from keras.layers import Embedding,LSTM,Dense,Dropout
from tensorflow.keras.callbacks import ReduceLROnPlateau
from keras.layers import Dense,Flatten,Embedding,Input,CuDNNLSTM,LSTM
from keras.layers import Dense, Dropout,Embedding,LSTM,Bidirectional
model=Sequential()
model.add(Embedding(vocab_size,32,input_length=20))
model.add(Bidirectional(LSTM(128)))
model.add(Dropout(0.50))
model.add(Dense(1,activation="sigmoid"))
model.compile(optimizer=Adam(learning_rate=3e-4),loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_7 (Embedding)     (None, 20, 32)            642112    
                                                                 
 bidirectional_5 (Bidirectio  (None, 256)              164864    
 nal)                                                            
                                                                 
 dropout_5 (Dropout)         (None, 256)               0         
                                                                 
 dense_5 (Dense)             (None, 1)                 257       
                                                                 
Total params: 807,233
Trainable params: 807,233
Non-trainable params: 0
_________________________________________________________________


In [ ]:
train_labels=df1.labels
dev_labels=df2.labels
model.fit(train_padding,train_labels,epochs=20,validation_data=(dev_padding,dev_labels))

Epoch 1/20
507/507 [==============================] - 9s 18ms/step - loss: 0.0170 - accuracy: 0.9888 - val_loss: 1.2303 - val_accuracy: 0.8495
Epoch 2/20
507/507 [==============================] - 9s 17ms/step - loss: 0.0182 - accuracy: 0.9885 - val_loss: 1.0645 - val_accuracy: 0.8530
Epoch 3/20
507/507 [==============================] - 9s 18ms/step - loss: 0.0169 - accuracy: 0.9891 - val_loss: 1.1368 - val_accuracy: 0.8490
Epoch 4/20
507/507 [==============================] - 9s 18ms/step - loss: 0.0158 - accuracy: 0.9876 - val_loss: 1.2317 - val_accuracy: 0.8500
Epoch 5/20
507/507 [==============================] - 9s 17ms/step - loss: 0.0161 - accuracy: 0.9884 - val_loss: 1.0487 - val_accuracy: 0.8584
Epoch 6/20
507/507 [==============================] - 9s 17ms/step - loss: 0.0156 - accuracy: 0.9893 - val_loss: 1.2765 - val_accuracy: 0.8525
Epoch 7/20
507/507 [==============================] - 9s 17ms/step - loss: 0.0171 - accuracy: 0.9875 - val_loss: 1.0709 - val_accuracy: 0.8476

In [ ]:
pred_result=model.predict(test_padding)

In [ ]:
import numpy as np
results=np.round(pred_result[:,0])
results

array([1., 1., 0., ..., 1., 0., 0.], dtype=float32)

### Output Prediction Result File

You will need to submit a prediction result file. It should have 2028 lines, every line should be either 0 or 1, which is your model's prediction on the respective test set instance.

In [ ]:
# suppose you had your model's predictions on the 2028 test cases read from test_enc_unlabeled.tsv, and 
#those results are in the list called 'results'
assert (len(results) == 2028)

In [ ]:
# make sure the results are not float numbers, but intergers 0 and 1
results = [int(x) for x in results]

In [ ]:
# write your prediction results to 'upload_predictions.txt' and upload that later
with open('upload_predictions.txt', 'w', encoding = 'utf-8') as fp:
    for x in results:
        fp.write(str(x) + '\n')